### ISSUE TITLE
[Bug Report] The bot is not responding to a command without any crash

### ISSUE THREAD

**Issue by pWoLiAn** [Clytage/whatsapp-bot#261]
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@open-wa/wa-automate' imported from /home/pwolian/Documents/whatsapp-bot/dist/structures/WhatsappBot.js
    at new NodeError (node:internal/errors:388:5)
    at packageResolve (node:internal/modules/esm/resolve:910:9)
    at moduleResolve (node:internal/modules/esm/resolve:959:20)
    at defaultResolve (node:internal/modules/esm/resolve:1174:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by pWoLiAn** [comment]
> 

```
{
  'whatsapp-bot': '1.0.0',
  npm: '8.12.1',
  node: '18.4.0',
  v8: '10.2.154.4-node.8',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.6',
  openssl: '3.0.3+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

```

**Comment by noxzym** [comment]
> > 
> 
> ```
> {
>   'whatsapp-bot': '1.0.0',
>   npm: '8.12.1',
>   node: '18.4.0',
>   v8: '10.2.154.4-node.8',
>   uv: '1.43.0',
>   zlib: '1.2.11',
>   brotli: '1.0.9',
>   ares: '1.18.1',
>   modules: '108',
>   nghttp2: '1.47.0',
>   napi: '8',
>   llhttp: '6.0.6',
>   openssl: '3.0.3+quic',
>   cldr: '41.0',
>   icu: '71.1',
>   tz: '2022a',
>   unicode: '14.0',
>   ngtcp2: '0.1.0-DEV',
>   nghttp3: '0.1.0-DEV'
> }
> ```
> 
> my OS is ubuntu

try remove `node_modules` and lock file, then reinstall project also dont fix audit error

**Comment by pWoLiAn** [comment]
ok i managed to start the bot but the listener is not detecting any commands
![image](https://user-images.githubusercontent.com/49567139/178137773-3baed29c-1517-46a9-8b64-fa0ebd364437.png)
im stuck here

**Comment by noxzym** [comment]
> ok i managed to start the bot but the listener is not detecting any commands ![image](https://user-images.githubusercontent.com/49567139/178137773-3baed29c-1517-46a9-8b64-fa0ebd364437.png) im stuck here

did you change the prefix?

**Comment by pWoLiAn** [comment]
No i didnt change."/ping" returns nothing

**Comment by mzrtamp** [comment]
I don't know when we can solve this issue, because it happens to us too.

**Comment by noxzym** [comment]
stale
