### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bkzutr90** [Clytage/whatsapp-bot#343]
npm start

> whatsapp-bot@1.0.0 start /root/qw
> node --es-module-specifier-resolution=node -r dotenv/config .

internal/modules/cjs/loader.js:331
      throw err;
      ^

Error: Cannot find module '/root/qw/dist'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:680:18)
    at resolveMainPath (internal/modules/run_main.js:12:25)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:65:24)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  path: '/root/qw/package.json',
  requestPath: '/root/qw'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot@1.0.0 start: `node --es-module-specifier-resolution=node -r dotenv/config .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-31T03_19_53_192Z-debug.log
root@iZt4n399yyn07pki1eijsdZ:~/qw# npm start

> whatsapp-bot@1.0.0 start /root/qw
> node --es-module-specifier-resolution=node -r dotenv/config .

internal/modules/cjs/loader.js:331
      throw err;
      ^

Error: Cannot find module '/root/qw/dist'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:680:18)
    at resolveMainPath (internal/modules/run_main.js:12:25)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:65:24)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  path: '/root/qw/package.json',
  requestPath: '/root/qw'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-bot@1.0.0 start: `node --es-module-specifier-resolution=node -r dotenv/config .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-31T03_20_01_677Z-debug.log
root@iZt4n399yyn07pki1eijsdZ:~/qw#

**Comment by Mednoob** [comment]
Have you ran `npm run build`? You need to build/compile the project first before starting the bot.
